services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 192.168.1.131 # Change this to your domain or IP address
    ports:
      - "80:80"      # HTTP port
      - "443:443"    # HTTPS port
      - "2222:22"      # SSH port
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.redoctober.icu'  # Change to your domain
    network_mode: "host"