services:
  nexus:
    image: sonatype/nexus3:3.70.1
    container_name: nexus3
    ports:
      - "8081:8081" # Expose Nexus UI on port 8081
      - "8082:8082" # docker repository http
      - "8083:8083" # docker repository https
    volumes:
      - nexus-data:/nexus-data # Persistent storage for Nexus data
      - ./nexus-backups:/nexus-data/backups # Bind mount for backups
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local
