services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    environment:
      # - LANG=de
      - WG_HOST=<🚨YOUR_SERVER_IP>
      - PASSWORD_HASH='<🚨YOUR_ADMIN_PASSWORD_HASH>'
      - PORT=51821
      - WG_PORT=51820
    volumes:
      # - ~/.wg-easy:/etc/wireguard
      - ~/docker/compose/app/wireguard-easy/ghcr/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
