services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3001  # Adjusted to your user ID
      - PGID=3000  # Adjusted to your group ID
      - TZ=Etc/UTC # Replace with your timezone
    volumes:
      - /mnt/media/configs/prowlarr/config:/config
      - /mnt/media:/md  # Mount books folder
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/configs/radarr/config:/config
      - /mnt/media:/md  # Mount movies folder
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/configs/sonarr/config:/config
      - /mnt/media:/md
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/configs/lidarr/config:/config
      - /mnt/media:/md
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/configs/readarr/config:/config
      - /mnt/media:/md
    ports:
      - 8787:8787
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=3001
      - PGID=3000
      - LOG_LEVEL=info
      - TZ=Etc/UTC
      - PORT=5055
    volumes:
      - /mnt/media/configs/jellyseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
    # runtime: nvidia
    volumes:
      - /mnt/media/configs/jellyfin/config:/config
      - /mnt/media/movies:/movies  # Mount movies folder
      - /mnt/media/shows:/shows  # Mount shows folder
      - /mnt/media/music:/music  # Mount music folder
      - /mnt/media/books:/books  # Mount books folder
    ports:
      - 8096:8096
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: 1
    #         capabilities: [gpu]


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /mnt/media/configs/qbittorrent/config:/config
      - /mnt/media:/md
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  default:
    driver: bridge