services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3001  # Adjusted to your user ID
      - PGID=3000  # Adjusted to your group ID
      - TZ=Etc/UTC # Replace with your timezone
    volumes:
      - ./prowlarr/config:/config
      - /mnt/media/books:/books  # Mount books folder
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/config:/config
      - ./mnt/media/downloads:/downloads
      - /mnt/media/movies:/movies  # Mount movies folder
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr/config:/config
      - /mnt/media/shows:/shows  # Mount shows folder
      - /mnt/media/downloads:/downloads  # Mount downloads folder
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./lidarr/config:/config
      - /mnt/media/music:/music  # Mount music folder
      - /mnt/media/downloads:/downloads  # Mount downloads folder
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:latest
    container_name: readarr
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./readarr/config:/config
      - /mnt/media/books:/books  # Mount books folder
      - /mnt/media/downloads:/downloads  # Mount downloads folder
    ports:
      - 8787:8787
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=3001
      - PGID=3000
      - LOG_LEVEL=info
      - TZ=Etc/UTC
      - PORT=5055
    volumes:
      - ./jellyseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3001
      - PGID=3000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/media/downloads:/downloads  # Mount downloads folder
      - /mnt/media/torrents:/torrents  # Mount torrents folder
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  default:
    driver: bridge