services:
  uptime-kuma:
    image: elestio/uptime-kuma:latest  # Use the latest image
    container_name: uptime-kuma       # Name the container
    ports:
      - "3001:3001"                   # Map port 3001 on the host to port 3001 in the container
    volumes:
      - ~/docker/compose/app/uptime-kuma/data:/app/data  # Map the host directory to the container's data directory
    restart: unless-stopped           # Automatically restart the container if it stops
